### ISSUE TITLE
New modal styling

### ISSUE THREAD

**Issue by carkod** [canonical/vanilla-framework#4883] opened 2023-10-02 14:51 UTC
## Pattern to amend

Modal. Specifically modal forms.

## Visual

Go to https://canonical.com/data/spark and click on "Contact us"

## Context and Expected result

[Original context](https://github.com/canonical/canonical.com/pull/1058#discussion_r1342700651).
We have new designs from @lyubomir-popov for the modals, using 50/50 layout, the X close button still to be sticky, but no lines below headings. @lyubomir-popov feel free to make any corrections.

**Comment by juanruitina** [comment] 2023-10-02 14:55
I had created already an issue for this ✌️

Duplicate of #4883

**Comment by juanruitina** [comment] 2023-10-02 14:57
Duplicate of #4878

**Closed** 2023-10-02 15:14 UTC
