### ISSUE TITLE
Upstream utility to add .5rem margin-top on images, aso they do not touch hrs with class p-rule

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4904] opened 2023-11-07 13:26 UTC
Often, we remove the margin-bottom on hrs, so they can sit as closely as possible to text. That causes images directly under those hrs (in columns adjacent to the text) to touch the hrs. 

I find myself copy pasting this utility to fix the problem, we have it on c.com, u.com, and am now adding it to microk8s. I think we should upstream it.

```
.p-image-wrapper {
  margin-top: $spv--medium;
}
```

**Comment by bartaz** [comment] 2023-11-07 13:53
If it's a utility, it should work on anything you put it on, not limited to images. If it's a component, it needs a proper definition of when to use that. 

Why is it also changing background with "partner" variant?

It should be defined on design system level what this is, so both designers and developers understand when to use it and why.

**Comment by lyubomir-popov** [comment] 2023-11-07 14:34
Utility I would say. I've removed the partners part, don't know wheree that came from - but also illustrates the problems with keeping utilities like thatt locally, people append irrelevant stuff.

**Comment by bartaz** [comment] 2023-11-09 07:32
Duplicate of #4791

**Comment by lyubomir-popov** [comment] 2023-11-09 07:55
closing as duplicatex

**Closed** 2023-11-09 07:54 UTC
Labels: WG: Proposal
