### ISSUE TITLE
Side bar items with sub pages are not clickable

### ISSUE THREAD

**Issue by nobuto-m** [canonical/vanilla-framework#5021] opened 2024-03-05 09:15 UTC
**Describe the bug**

Side bar items with sub pages are not clickable as a hyperlink, but the only arrow part is clickable. I'm seeing this as issues in multiple sites with the vanilla framework so I'm filing this to the framework although I'm not sure if this behavior comes from the framework itself or from the consumer side of the framework.

e.g.

- https://github.com/canonical/ubuntu.com/issues/13257
- https://github.com/canonical/charmhub.io/issues/1775

**To Reproduce**

1. Visit https://ubuntu.com/ceph/docs
2. Try to click "Install" in the side bar
3. Nothing happens

**Expected behavior**

The `Install` text should be clickable and expand the sub menu of it

**Screenshots**

[The `Install` text is not clickable but only the arrow button is]
![image](https://github.com/canonical/vanilla-framework/assets/4356209/006b1813-63fe-45af-850b-76cc7d02f470)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04 LTS (development)
- Browser Firefox
- Version 123.0

**Comment by bartaz** [comment] 2024-03-13 09:48
Thanks for the report. This behaviour is currently by design. 

One of the requirements for the expandable navigation was to be able to link to a documentation page and being expandable. That's why clicking on navigation item (like "Install") is separate from expanding it.

In this particular implementation it seems that "Install" doesn't have a paged linked to, which is not a recommended use of this component. For situations like this we have the "accordion" version of side navigation, where navigation items are expandable, but don't navigate to pages.

https://vanillaframework.io/docs/examples/patterns/side-navigation/accordion

I see this issue being reported by different people via various channels, so I'll bring it up to Vanilla Working Group to see how we can better address it.

**Comment by danielmutis** [comment] 2024-03-20 10:14
WG: The behaviour of the side navigation was intended to be consistent regardless of whether there is a page or not on the nav item. The design decision from the documentation team was that it is essential that every item of the navigation is also a page. By having the chevron behave sometimes in one way and sometimes in another is not recommended.

@evildmp just so you are aware.

**Comment by nobuto-m** [comment] 2024-03-20 11:25
What does that mean practically? Is there any action to be taken by the framework or is the issue in the consumer side of the framework effectively?

**Comment by bartaz** [comment] 2024-03-20 11:56
To my understanding this is a content issue. For this component to be used as intended all items in the navigation should be linked to a page.

**Comment by danielmutis** [comment] 2024-04-17 09:23
WG: This depends on the documentation team's decisions on how the side nav behaves. We will close this issue, unless there is an agreement on changing the approach with docs.

**Closed by danielmutis** 2024-04-17 09:23 UTC
Labels: Bug 🐛
