### ISSUE TITLE
Heading anchor links styling

### ISSUE THREAD

**Issue by petesfrench** [canonical/vanilla-framework#5036] opened 2024-03-27 08:43 UTC
## Visual

Normal:
![image](https://github.com/canonical/vanilla-framework/assets/58276363/9ee2208c-7e56-4061-a958-82ec192bf8cd)
Hover:
![image](https://github.com/canonical/vanilla-framework/assets/58276363/5b890f1e-6e7a-4d03-b8b0-44943cd0c059)

## Context

All docs

## SCSS example
```
.p-anchor-link {
  color: $color-dark;

  &:visited {
    color: $color-dark;
  }

  &:after {
    @extend .p-icon--anchor;
    content: "¶";
    display: inline-block;
    padding: 1rem;
    top: 0.6rem;
    visibility: hidden;
    margin-left: 0.75rem;
  }

  &:hover {
    &::after {
      visibility: visible;
    }
  }
}
``` 
```
<h2><a class="p-anchor-link" href="#in-this-documentation-1" name="in-this-documentation-1">In this documentation</a></h2>
```

**Comment by danielmutis** [comment] 2024-04-03 09:28
WG: @petesfrench @juanruitina to provide a couple of examples of how this has been implemented in other DSs and we could look into commissioning a design for the icon.

**Comment by juanruitina** [comment] 2024-04-03 10:17
I've had a look at a handful of websites that have heading anchor links:

- All websites except MDN use the link icon (🔗). I suggest that we go ahead and commission that icon.
- Most just link to the heading as we do. Only Google's copy the link to the clipboard. ✅
- Only MDN and GitHub make the whole heading clickable as we do, most just make the icon clickable. But I don't think our approach does any harm.
- Most show the icon on hover as we do ✅
- Some show the icon to the left of the heading, some to the right. I'm not sure which approach is best, but it seems to the right is simpler, even if it can potentially result in wrapping. But maybe this requires some testing with real content.

### Benchmarking

[Discourse](https://discourse.ubuntu.com/t/weekly-status-341/43794): icon to the left, shows on hover, only icon is linked, points to anchor

<img width="404" alt="Screenshot 2024-04-03 at 11 35 10" src="https://github.com/canonical/vanilla-framework/assets/1409729/487e4a06-ef38-4aba-9d01-a06c96c82d22">

[Carbon design system](https://carbondesignsystem.com/components/link/usage/): same as Discourse

<img width="402" alt="Screenshot 2024-04-03 at 11 34 09" src="https://github.com/canonical/vanilla-framework/assets/1409729/5eaaa674-5886-4e4e-bb6b-f0b03f2045f3">

[Apple Developer](https://developer.apple.com/design/human-interface-guidelines/color#Inclusive-color): same as Discourse (but icon to the right)

<img width="382" alt="Screenshot 2024-04-03 at 11 52 28" src="https://github.com/canonical/vanilla-framework/assets/1409729/1a031a0e-5f5a-418c-81e4-14c31ee869ac">

[React documentation](https://react.dev/learn): same as Discourse (but icon to the right)

<img width="544" alt="Screenshot 2024-04-03 at 11 28 20" src="https://github.com/canonical/vanilla-framework/assets/1409729/51f920ef-7da9-4d57-a4e0-13a2e0a02c34">

[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attributes): hash to the left on hover, both heading and icon point to anchor

<img width="302" alt="Screenshot 2024-04-03 at 12 14 58" src="https://github.com/canonical/vanilla-framework/assets/1409729/c4957203-5259-47bc-8e72-31e304b7dd5b">

[GitHub documentation](https://docs.github.com/en/get-started/start-your-journey/about-github-and-git): icon to the right, always visible, both heading and icon point to anchor

<img width="507" alt="Screenshot 2024-04-03 at 11 31 44" src="https://github.com/canonical/vanilla-framework/assets/1409729/f58686eb-8957-40d0-9e8b-dd1aa91498c1">: 

[Material](https://m3.material.io/components/buttons/specs): icon to the left shows on hover, copies link

<img width="457" alt="Screenshot 2024-04-03 at 11 37 48" src="https://github.com/canonical/vanilla-framework/assets/1409729/d7a79893-d77f-4092-b5f2-09ecf506a3de">

[Google Cloud documentation](https://cloud.google.com/docs/overview): same as Material (unsurprisingly), icon to the right

<img width="523" alt="Screenshot 2024-04-03 at 11 32 37" src="https://github.com/canonical/vanilla-framework/assets/1409729/4145e8df-1029-4bb4-bbd3-b597fa3df789">

**Comment by bartaz** [comment] 2024-04-03 10:26
Gov.uk doesn't seem to use anchor links on headings. Headings have ids (so can be linked to), but anchor is only accessible via table of contents, not the heading itself.

https://www.gov.uk/government/news/bird-flu-avian-influenza-latest-situation-in-england#cases

<img width="642" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/10fdc3f0-4ab9-4a5e-ae64-51360a7ae324">

**Comment by petesfrench** [comment] 2024-04-03 13:26
@bartaz The request to have the headings clickable comes from the documentation team

**Comment by bartaz** [comment] 2024-04-03 13:36
> @bartaz The request to have the headings clickable comes from the documentation team

Yes, I know. We are just gathering examples of how others are doing something similar.

**Comment by bartaz** [comment] 2024-04-03 16:45
Hmm… we have the icon of that name, but it's a chevron… I can try to track down if that was a deliberate decision or just some mistake:

<img width="364" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/125b16ee-acb9-49ce-b7ef-b1e7c6596ade">

**Comment by bartaz** [comment] 2024-04-03 16:57
We have the icon in code snippet component, it looks like a bug that it got replaced to chevon. We can bring it back.

<img width="1007" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/9482d4af-3302-40a3-8e74-6aba86ae8f10">

**Comment by danielmutis** [comment] 2024-04-17 09:21
WG: Link icon is a good fit.

**Comment by petesfrench** [comment] 2024-04-19 13:57
@bartaz What do we have to do to get this upstreamed to vanilla?

**Comment by bartaz** [comment] 2024-04-22 07:39
@petesfrench Create a PR and we can take it from there in review.

**Comment by bartaz** [comment] 2024-04-22 07:40
It may be good to verify it first by some local implementation on one of the docs websites, to see if that works as intended in the context of the docs.

**Comment by bartaz** [comment] 2024-05-29 09:24
@petesfrench What's the status of this? You had some PR for that on one of docs websites, but I don't know where it was and has it landed?

**Comment by bartaz** [comment] 2024-09-25 07:17
Done in https://github.com/canonical/vanilla-framework/pull/5120

**Closed** 2024-09-25 07:17 UTC
Labels: WG: Validated
