### ISSUE TITLE
Unable to run the dotrun snap to run the site locally

### ISSUE THREAD

**Issue by Jim-Dillon** [canonical/vanilla-framework#4779] opened 2023-06-07 10:08 UTC
**Describe the bug**

Hi all, I'm trying to open the project locally and I'm having an issue with running the dotrun snap. For reference, my OS is macOS Ventura 13.4.

**To Reproduce**

I've followed the instructions from the READMEs: 

- Install and run Docker 
- Install Homebrew 
- Run the two commands under the [Mac](https://github.com/canonical/dotrun/blob/main/README.md) section of the Dotrun README

Then finally when I run a `dotrun` command, I get the following error:

"Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'"
"Dotrun needs Docker to work, please check if Docker is installed and running"

My Docker is installed and running so I assume the issue is stemming from the first line. I'm wondering if anyone has encountered this issue before and can spot an oversight from myself at all. 

Thank you!

**Comment by bartaz** [comment] 2023-06-07 10:44
Hi @Jim-Dillon , thanks for reaching out.

Seeing that you have a similar issue https://github.com/canonical/canonical.com/issues/881 it seems there may be some issue with dotrun itself, and not necessarily canonical.com or vanilla framework projects.

Searching for the error you mentioned also shows quite recent python dependency issue which may be happening, but I haven't seen it myself in our projects before: https://github.com/docker/docker-py/issues/3113

Could you run `pip3 show dotrun` to verify which version of dotrun you are using?
And I guess it may he helpful to show all commands that you are running and their output.

Thanks!

**Comment by Jim-Dillon** [comment] 2023-06-07 13:07
Thanks for your help, @bartaz! 

Running `pip show dotrun` is showing version 2.1.0 of dotrun. Here are a list of the commands I've run from the READMEs and their output: 

1. Install Docker (I've just run `docker version` to confirm it's installed)

<img width="453" alt="Screenshot 2023-06-07 at 13 43 37" src="https://github.com/canonical/vanilla-framework/assets/95416961/b7557a13-5d24-430a-905b-f9509af1461c">


2. Install Homebrew

<img width="945" alt="Screenshot 2023-06-07 at 13 52 16" src="https://github.com/canonical/vanilla-framework/assets/95416961/a4d2dce3-7526-48d6-ac72-6cb2fdfd3ac8">

3. Run the two commands from the [dotrun README](https://github.com/canonical/dotrun/blob/main/README.md)

<img width="492" alt="Screenshot 2023-06-07 at 13 55 19" src="https://github.com/canonical/vanilla-framework/assets/95416961/4ed20117-c087-4b9c-8241-cd3e400668ef">

<img width="942" alt="Screenshot 2023-06-07 at 13 56 54" src="https://github.com/canonical/vanilla-framework/assets/95416961/e9af6cdf-c66f-4c8c-b48c-f86dca95957e">

4. Run the dotrun command 

<img width="783" alt="Screenshot 2023-06-07 at 13 59 22" src="https://github.com/canonical/vanilla-framework/assets/95416961/10adca2a-2101-4bd1-aa8b-612490ea7584">

Thanks again!

**Comment by bartaz** [comment] 2023-06-07 18:36
@Jim-Dillon It seems to all look correct. I don't know why dotrun fails to run.

I'm on Ventura Mac as well, and I don't think I needed to install Python via brew. I think at some point MacOS started to ship with Python3.

Cause the only difference between your setup and mine I see is the python version. I have 3.9.6 from MacOS dev tools. You seem to have 3.11.x from brew.

Maybe you could try uninstalling python from brew (`brew uninstall python`) and installing the one that comes with mac dev tools `xcode-select --install` (as per https://discussions.apple.com/thread/254320722). This should bring your python version to 3.9.6 that I have and hopefully this setup would work.

If not there may be some other differences we haven't noticed.

Overall I believe that the issue is somewhere around Python, because the issue comes from within a Python module dependency.

**Comment by Jim-Dillon** [comment] 2023-06-08 16:11
@bartaz It must be a Python issue like you say. 

I've uninstalled and reinstalled Python to match your set up and still encounter an error with running `dotrun`. When I check the `pip3 list` it shows that dotrun is included in the package, but then when I run `dotrun` it doesn't acknowledge it: 

<img width="422" alt="Screenshot 2023-06-08 at 16 57 57" src="https://github.com/canonical/vanilla-framework/assets/95416961/88320447-df73-446a-8a47-c02967db4d8f">

<img width="793" alt="Screenshot 2023-06-08 at 16 58 17" src="https://github.com/canonical/vanilla-framework/assets/95416961/dcd90086-796f-4f1c-b9b2-382a0a7efc33">

There might be an issue with dotrun being added to my PATH, as when I run `echo $PATH` there is no mention of dotrun.

**Comment by anthonydillon** [comment] 2023-06-27 11:06
This can be replicated by installing `dotrun` and running this project on codespaces.

**Comment by bartaz** [comment] 2023-06-28 08:36
It seems to be an issue with dotrun and/or some python dependencies. I used to run Vanilla (and other repos) in codespaces with dotrun and it worked fine, now I can confirm it doesn't work.

As it doesn't seem to be an issue with Vanilla directly, I opened a bug on dotrun repo (https://github.com/canonical/dotrun/issues/117) and will close this one.

**Closed by bartaz** 2023-06-28 08:36 UTC
