### ISSUE TITLE
Stepped lists always show zero count for nested ordered lists

### ISSUE THREAD

**Issue by carkod** [canonical/vanilla-framework#4998] opened 2024-02-15 17:58 UTC
**Describe the bug**

When we add an ordered list nested inside of the `p-stepped-list__content` the numbers always start from 0.x, no matter what step we are in. Interestingly, this only happens when we use `p-stepped-list---detailed` or when use `p-list--divided`

**To Reproduce**

1. Go to https://codepen.io/carkod/pen/mdovJWr
2. Scroll to step 4. You can see that the nested ordered list starts from 0.1, instead it should show 4.1

**Expected behavior**

If you change the top parent class from `p-stepped-list--detailed` to `p-stepped-list`, or the nested list from `p-list--divided` to `p-list` it actually works! That's why this is filed as a bug

**Screenshots**
![Screenshot from 2024-02-15 17-54-40](https://github.com/canonical/vanilla-framework/assets/14939793/f65be225-8cd1-4e9d-911a-e8d94bcc3c74)

**Comment by bartaz** [comment] 2024-02-15 18:09
Thanks. Seems like there is some counter reset happening somewhere. I wonder if it was intended for a reason.

**Comment by bartaz** [comment] 2024-02-27 12:42
It seems that the CSS counter inside the p-list--divided conflicts with some CSS reset that we do in stepped list (needs a bit more investigation).

See: https://github.com/search?q=repo%3Acanonical%2Fvanilla-framework%20counter-reset&type=code

**Comment by bartaz** [comment] 2024-03-13 09:50
Fixed in #5011

**Closed by bartaz** 2024-03-13 09:50 UTC
Labels: Bug 🐛, Guest dev 🤝
