### ISSUE TITLE
Logo section: update to 1col per logo (or provide small variant)

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4667] opened 2023-02-24 10:00 UTC
## Pattern to amend

I've been asked to make these smaller, and we already do so on e.g. the pro page
![image](https://user-images.githubusercontent.com/2741678/221149657-2ae3db00-02c9-42d1-96fb-0c1edab8f3af.png)

We already do so on e.g. the pro page: 
![image](https://user-images.githubusercontent.com/2741678/221149816-61f3e9d8-868b-492f-9825-0681180fb37b.png)

Wondering if we should maybe update the component to do that out of the box? Or at least provide  --small version for logos that are not particularly important, or too many?

**Comment by bartaz** [comment] 2023-02-24 12:17
Duplicate of #4642

**Closed by bartaz** 2023-02-24 12:17 UTC
Labels: Guest dev 🤝
