### ISSUE TITLE
Pagination overflows on smalle screens 

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4813] opened 2023-06-29 10:31 UTC
(low priority as it can easily be patched, not for 4.0)
![image](https://github.com/canonical/vanilla-framework/assets/2741678/9dc8dc5c-4116-42df-bcce-90143dc70e45)

**Comment by bartaz** [comment] 2024-01-25 16:22
Duplicate of #4820

**Closed** 2024-04-30 15:04 UTC
