### ISSUE TITLE
[Accessibility Docs] Quotes

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#4060] opened 2021-10-13 16:24 UTC
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Quotes](https://vanillframework.io/docs/patterns/pull-quote)

**Comment by bethcollins92** [comment] 2022-01-19 15:54
[Accessibility doc](https://docs.google.com/document/d/1pRncWWbbpJtQSM-pQ-YFeKw8hNdxErFOzCtiISjTbRc/edit#) for now, but it's blocked by this [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/4263)

**Comment by bethcollins92** [comment] 2022-04-26 15:17
The issue is now fixed, so the doc is ready to be reviewed and added to the site

**Closed as completed** 2022-04-28 13:04 UTC
Labels: Review: Code +1, Review: UX +1, Accessibility
